In [1]:
import pandas as pd

In [2]:
#unione dei dataset (verranno divisi poi per il test e per il training)
features = pd.concat([pd.read_csv('../../dataset_v1/'+labels + '.csv') for labels in ['hand_opened', 'hand_closed', 'one', 'spiderman']])
featuresv2 = pd.concat([pd.read_csv('../../dataset_v2/'+labels + '_v2.csv') for labels in ['hand_opened', 'hand_closed', 'one', 'spiderman']])
dataset = pd.concat([features,featuresv2])

In [3]:
#sostituzione della colonna handedness con la colonna is_right (0|1) 
dataset['is_right'] = 0
dataset.loc[dataset['handedness'] == 'Right', 'is_right'] = 1
dataset[dataset['is_right']== 1]
dataset.drop(columns=['handedness'], inplace=True)

In [4]:
dataset.head(3)

,x0,y0,z0,x1,y1,z1,x2,y2,z2,x3,...,z18,x19,y19,z19,x20,y20,z20,handedness,gesture,is_right
0,0.436459,1.029835,7.257333e-07,0.515812,1.007966,-0.044799,0.582073,0.953413,-0.075028,0.639527,...,-0.122048,0.312438,0.671181,-0.140857,0.291136,0.612210,-0.150946,Left,hand_opened,0
1,0.440497,1.037069,6.988757e-07,0.521399,1.010074,-0.041076,0.587852,0.957393,-0.071538,0.646615,...,-0.133241,0.324201,0.673027,-0.149851,0.304530,0.609800,-0.159262,Left,hand_opened,0
2,0.446310,1.041283,7.072587e-07,0.528277,1.014194,-0.039648,0.595027,0.958403,-0.067755,0.655301,...,-0.124702,0.332755,0.677684,-0.140871,0.313983,0.614861,-0.149919,Left,hand_opened,0

In [9]:
# replace 'gesture' column by multiple dummy columns
labels = pd.get_dummies(dataset['gesture'])
#eliminazione della label dal dataset
dataset.drop(columns=['gesture'], inplace=True)

In [10]:
dataset.columns

Index(['x0', 'y0', 'z0', 'x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'x3', 'y3', 'z3',
       'x4', 'y4', 'z4', 'x5', 'y5', 'z5', 'x6', 'y6', 'z6', 'x7', 'y7', 'z7',
       'x8', 'y8', 'z8', 'x9', 'y9', 'z9', 'x10', 'y10', 'z10', 'x11', 'y11',
       'z11', 'x12', 'y12', 'z12', 'x13', 'y13', 'z13', 'x14', 'y14', 'z14',
       'x15', 'y15', 'z15', 'x16', 'y16', 'z16', 'x17', 'y17', 'z17', 'x18',
       'y18', 'z18', 'x19', 'y19', 'z19', 'x20', 'y20', 'z20', 'handedness',
       'is_right'],
      dtype='object')

In [11]:
labels.columns

Index(['hand_closed', 'hand_opened', 'one', 'spiderman'], dtype='object')

      hand_closed  hand_opened  one  spiderman
0               0            1    0          0
1               0            1    0          0
2               0            1    0          0
3               0            1    0          0
4               0            1    0          0
...           ...          ...  ...        ...
2570            0            0    0          1
2571            0            0    0          1
2572            0            0    0          1
2573            0            0    0          1
2574            0            0    0          1

[12897 rows x 4 columns]

,x0,y0,z0,x1,y1,z1,x2,y2,z2,x3,...,x18,y18,z18,x19,y19,z19,x20,y20,z20,is_right
0,0.436459,1.029835,7.257333e-07,0.515812,1.007966,-0.044799,0.582073,0.953413,-0.075028,0.639527,...,0.340789,0.732432,-0.122048,0.312438,0.671181,-0.140857,0.291136,0.612210,-0.150946,0
1,0.440497,1.037069,6.988757e-07,0.521399,1.010074,-0.041076,0.587852,0.957393,-0.071538,0.646615,...,0.350390,0.736804,-0.133241,0.324201,0.673027,-0.149851,0.304530,0.609800,-0.159262,0
2,0.446310,1.041283,7.072587e-07,0.528277,1.014194,-0.039648,0.595027,0.958403,-0.067755,0.655301,...,0.358669,0.740706,-0.124702,0.332755,0.677684,-0.140871,0.313983,0.614861,-0.149919,0
3,0.448763,1.046175,7.230610e-07,0.531748,1.015607,-0.036767,0.597670,0.957050,-0.063146,0.658217,...,0.358890,0.731508,-0.117686,0.334178,0.666702,-0.133134,0.316719,0.603039,-0.141529,0
4,0.435180,1.034045,7.101457e-07,0.518623,1.002030,-0.038800,0.586553,0.944859,-0.066296,0.647342,...,0.342035,0.720671,-0.117990,0.317424,0.655888,-0.134349,0.300305,0.593098,-0.143779,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2570,0.602078,0.852922,-7.846045e-08,0.608815,0.807297,0.011275,0.627490,0.770824,0.013212,0.651063,...,0.698148,0.755168,-0.023164,0.712590,0.737647,-0.021225,0.722650,0.717991,-0.018370,0
2571,0.660266,0.778544,-2.960130e-08,0.656586,0.751477,-0.006759,0.662055,0.721882,-0.012962,0.673761,...,0.707774,0.768801,-0.033235,0.718398,0.755269,-0.031017,0.722204,0.742989,-0.028238,0
2572,0.606757,0.858716,-4.567915e-08,0.610129,0.811361,0.010068,0.627306,0.772432,0.010406,0.650114,...,0.702449,0.771929,-0.019092,0.716963,0.756239,-0.014571,0.727190,0.738662,-0.010092,0
2573,0.646223,0.818501,1.768732e-07,0.643929,0.787898,-0.005218,0.651390,0.756627,-0.012481,0.666857,...,0.701969,0.774412,-0.040618,0.712358,0.763526,-0.038379,0.717725,0.754387,-0.036133,0
2574,0.604698,0.860522,-3.802835e-08,0.608647,0.813992,0.009021,0.626795,0.775140,0.009089,0.650780,...,0.702483,0.772313,-0.017905,0.717390,0.756967,-0.013670,0.727689,0.739745,-0.009425,0

Index(['x0', 'y0', 'z0', 'x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'x3', 'y3', 'z3',
       'x4', 'y4', 'z4', 'x5', 'y5', 'z5', 'x6', 'y6', 'z6', 'x7', 'y7', 'z7',
       'x8', 'y8', 'z8', 'x9', 'y9', 'z9', 'x10', 'y10', 'z10', 'x11', 'y11',
       'z11', 'x12', 'y12', 'z12', 'x13', 'y13', 'z13', 'x14', 'y14', 'z14',
       'x15', 'y15', 'z15', 'x16', 'y16', 'z16', 'x17', 'y17', 'z17', 'x18',
       'y18', 'z18', 'x19', 'y19', 'z19', 'x20', 'y20', 'z20', 'is_right'],
      dtype='object')

In [21]:
# calcola il minimo tra le n colonne per ogni riga
min_values = dataset[[
    'x0', 'y0', 'z0', 'x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'x3', 'y3', 'z3',
       'x4', 'y4', 'z4', 'x5', 'y5', 'z5', 'x6', 'y6', 'z6', 'x7', 'y7', 'z7',
       'x8', 'y8', 'z8', 'x9', 'y9', 'z9', 'x10', 'y10', 'z10', 'x11', 'y11',
       'z11', 'x12', 'y12', 'z12', 'x13', 'y13', 'z13', 'x14', 'y14', 'z14',
       'x15', 'y15', 'z15', 'x16', 'y16', 'z16', 'x17', 'y17', 'z17', 'x18',
       'y18', 'z18', 'x19', 'y19', 'z19', 'x20', 'y20', 'z20'
    ]].apply(min, axis=1)
min_values

0      -0.150946
1      -0.159262
2      -0.149919
3      -0.141529
4      -0.143779
          ...
2570   -0.023164
2571   -0.040912
2572   -0.019092
2573   -0.046231
2574   -0.017905
Length: 12897, dtype: float64

In [22]:
dataset[[
    'x0', 'y0', 'z0', 'x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'x3', 'y3', 'z3',
       'x4', 'y4', 'z4', 'x5', 'y5', 'z5', 'x6', 'y6', 'z6', 'x7', 'y7', 'z7',
       'x8', 'y8', 'z8', 'x9', 'y9', 'z9', 'x10', 'y10', 'z10', 'x11', 'y11',
       'z11', 'x12', 'y12', 'z12', 'x13', 'y13', 'z13', 'x14', 'y14', 'z14',
       'x15', 'y15', 'z15', 'x16', 'y16', 'z16', 'x17', 'y17', 'z17', 'x18',
       'y18', 'z18', 'x19', 'y19', 'z19', 'x20', 'y20', 'z20'
    ]] = dataset[[
    'x0', 'y0', 'z0', 'x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'x3', 'y3', 'z3',
       'x4', 'y4', 'z4', 'x5', 'y5', 'z5', 'x6', 'y6', 'z6', 'x7', 'y7', 'z7',
       'x8', 'y8', 'z8', 'x9', 'y9', 'z9', 'x10', 'y10', 'z10', 'x11', 'y11',
       'z11', 'x12', 'y12', 'z12', 'x13', 'y13', 'z13', 'x14', 'y14', 'z14',
       'x15', 'y15', 'z15', 'x16', 'y16', 'z16', 'x17', 'y17', 'z17', 'x18',
       'y18', 'z18', 'x19', 'y19', 'z19', 'x20', 'y20', 'z20'
    ]].subtract(min_values, axis=0)

In [23]:
dataset

,x0,y0,z0,x1,y1,z1,x2,y2,z2,x3,...,x18,y18,z18,x19,y19,z19,x20,y20,z20,is_right
0,0.587404,1.180781,0.150946,0.666758,1.158911,0.106146,0.733018,1.104358,0.075917,0.790473,...,0.491735,0.883378,0.028898,0.463384,0.822127,0.010088,0.442082,0.763156,0.000000,0
1,0.599760,1.196331,0.159263,0.680662,1.169336,0.118187,0.747114,1.116655,0.087724,0.805877,...,0.509652,0.896067,0.026022,0.483463,0.832289,0.009411,0.463792,0.769062,0.000000,0
2,0.596229,1.191202,0.149919,0.678195,1.164113,0.110271,0.744946,1.108322,0.082164,0.805219,...,0.508588,0.890624,0.025217,0.482674,0.827602,0.009048,0.463902,0.764779,0.000000,0
3,0.590293,1.187705,0.141530,0.673277,1.157136,0.104763,0.739199,1.098579,0.078383,0.799746,...,0.500419,0.873038,0.023843,0.475708,0.808231,0.008395,0.458248,0.744568,0.000000,0
4,0.578959,1.177824,0.143780,0.662401,1.145809,0.104979,0.730332,1.088638,0.077483,0.791121,...,0.485814,0.864449,0.025789,0.461202,0.799666,0.009430,0.444084,0.736877,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2570,0.625242,0.876086,0.023164,0.631979,0.830462,0.034439,0.650654,0.793989,0.036377,0.674227,...,0.721312,0.778332,0.000000,0.735754,0.760811,0.001939,0.745815,0.741156,0.004795,0
2571,0.701179,0.819456,0.040912,0.697499,0.792389,0.034153,0.702968,0.762795,0.027951,0.714673,...,0.748686,0.809714,0.007678,0.759310,0.796181,0.009896,0.763116,0.783901,0.012675,0
2572,0.625849,0.877808,0.019092,0.629221,0.830452,0.029160,0.646398,0.791524,0.029497,0.669205,...,0.721541,0.791021,0.000000,0.736055,0.775331,0.004521,0.746282,0.757754,0.009000,0
2573,0.692454,0.864732,0.046231,0.690160,0.834129,0.041013,0.697621,0.802858,0.033750,0.713088,...,0.748200,0.820643,0.005614,0.758590,0.809758,0.007852,0.763956,0.800619,0.010099,0
2574,0.622603,0.878427,0.017905,0.626552,0.831897,0.026926,0.644700,0.793045,0.026994,0.668685,...,0.720388,0.790218,0.000000,0.735295,0.774872,0.004235,0.745594,0.757650,0.008480,0